In [1]:
import numpy as np

In [6]:
"""
Нужно найти из массива самый большой его элемент 
"""
arr = np.array([10, 23, 3, 8, 7, 4, 9])

In [3]:
# Способ по индексу
m = max(arr)
ind = -1
for i in range(arr.shape[0]):
    if arr[i] == m:
        ind = i
        break
ind

6

In [ ]:
"""
В математике эта операция называется argmax 
"""
np.argmax(arr)

In [ ]:
# Аналогично - минимум
np.argmin(arr)

In [ ]:
"""
Операцию можно сделать многомерной 
"""
arr = np.arange(16).reshape(-1, 4)[::-1]
arr

In [ ]:
np.argmin(arr)

In [ ]:
np.argmin(arr, axis=0)

In [16]:
"""inf и nan"""

nan_inf_arr = np.array([1, 2, np.inf, 4, 5, np.nan, 7, 8, np.nan])
nan_inf_arr

array([ 1.,  2., inf,  4.,  5., nan,  7.,  8., nan])

In [17]:
np.isinf(nan_inf_arr)

array([False, False,  True, False, False, False, False, False, False])

In [18]:
np.isnan(nan_inf_arr)

array([False, False, False, False, False,  True, False, False,  True])

In [19]:
np.amax(nan_inf_arr)

nan

In [20]:
np.nanmax(nan_inf_arr)

inf

In [22]:
arr = np.array([[1, 2, 3], [32, 8, 12], [45, 2, 9]])
arr

array([[ 1,  2,  3],
       [32,  8, 12],
       [45,  2,  9]])

In [23]:
np.median(arr)

8.0

In [26]:
"""
Квантиль (иногда фрактиль) – граница деления Выборки (Sample) или Совокупности (Population) 
на равные по размеру смежные подгруппы. 
Это также относится к разделению распределения вероятностей на области равного размера: 
Площади многоугольников, разделенные пунктирными проекциями, равны. 
Медиана – это тоже квантиль, которая расположена так, чтобы ровно половина данных (0,5) была левее медианы. 
"""

np.quantile(arr, 0.05)

1.4

In [27]:
# Среднее арифметическое
np.mean(arr)

12.666666666666666

In [28]:
# Average можно брать с весами
arr = np.arange(1, 10)
weights = 1/arr
np.average(arr, weights=weights)

3.181371861411138

In [29]:
# Стандартное отклонение
np.std(arr)

2.581988897471611

In [30]:
"""
Корреля́ция (от лат. correlatio «соотношение»), или корреляцио́нная зави́симость — 
статистическая взаимосвязь двух или более случайных величин 
(либо величин, которые можно с некоторой допустимой степенью точности считать таковыми), 
при этом изменения значений одной или нескольких из этих величин сопутствуют систематическому 
изменению значений другой или других величин. 
"""

# Корреляции

a = np.arange(10)
b = a[::-1]

np.corrcoef(a, b)

array([[ 1., -1.],
       [-1.,  1.]])

In [31]:
noisy_b = b + np.random.randn(b.shape[0]) * b.std() / 10
noisy_b

array([ 8.9813715 ,  7.99171637,  6.75349668,  6.00763817,  5.13521124,
        4.01747262,  3.13883123,  1.90373143,  1.31252308, -0.38012142])

In [32]:
np.corrcoef(a, b + noisy_b)

array([[ 1.        , -0.99947214],
       [-0.99947214,  1.        ]])