In [1]:
import numpy as np

"""
Все одномерные массивы могут быть представлены, как элементы многомерного
линейного пространства. А двумерные - как элементы пространства матриц определенного размера.
"""
from numpy import linalg as linalg

In [10]:
"""
-Произведение матриц
-Возведение в степень 
"""

A = np.ones((4, 3))
B = np.full((3, 5), 3)
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
B

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
# Переумножение матриц осуществляется одной из этих функций np.dot, np.matmul
np.matmul(A, B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [12]:
np.dot(A, B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [13]:
# Возведение матрицы в степень
A = np.ones((3, 3))
linalg.matrix_power(A, 2)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [2]:
A = np.ones(5)
A

array([1., 1., 1., 1., 1.])

In [3]:
linalg.norm(A)

2.23606797749979

In [4]:
np.sqrt(5)

2.23606797749979

In [5]:
"""
Собственные числа и мобственные векторы 
"""
A = np.array([[-1, -6], [2, 6]])
A

array([[-1, -6],
       [ 2,  6]])

In [6]:
linalg.eig(A)

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

In [7]:
# Система линейных уравнений
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 0])
linalg.solve(A, b)

array([-10. ,   7.5])