In [1]:
import numpy as np

# создание массива
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# копирование массива в другой
B = A.copy()
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# Построение диапазона чисел от From (включая) до To (не включая) с щагом Step
import numpy as np

From = 2.5
To = 7
Step = 0.5
A = np.arange(From, To, Step)
A

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [3]:
# Функция создания массива определенной формы, заполненного константами
A = np.full((5, 6), 4.5)
A

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [4]:
# Создание пустого массива указанной формы
B = np.empty((5, 6))
B

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [5]:
# Создание единичнодиагонального квадратного массива
C = np.identity(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Создание нулевого/единичного массива с заданными размерами
A = np.zeros((2, 3, 2))
B = np.ones((3, 2))
C = np.eye(5)
A

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# Если прописать оператор сложения, то получим конкатенацию
A = [1, 2, 3, 4,]
B = [5, 6, 7, 8, 9]
A + B

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
A = np.ones((3, 3))
B = np.full_like(A, 4)
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [12]:
A * B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [13]:
# Если один из аргументов - константа
A = np.array([[-1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = -2
A

array([[-1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [14]:
A + B

array([[-3.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [15]:
np.isinf(A/B)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])